### ISSUE TITLE
Unexpected write to Monster.Config when simulation is setup and .run is called

### ISSUE THREAD

**Issue by jakthra** [Sonohi/monster#106]
A few modifications to the config is made when the simulation is setup. This should not happen. The Config should be a static read object and nothing else. The rest of the parameters should be moved different class properties in the simulation class. The parameters in question are:

* Simulation.Config.Plot
* Simulation.Config.Runtime

I propose a solution where the above properties are moved to

* Simulation.Config.Plot --> Simulation.Plot
* Simulation.Config.Runtime --> Simulation.RunTime

**Comment by artuso0matteo** [comment]
Closing as it is addressed by #114
