### ISSUE TITLE
Estimated channel conditions and actual channel conditions

### ISSUE THREAD

**Issue by jakthra** [Sonohi/monster#108]
both the estimated and actual channel conditions are stored in the receiver objects, e.g. UeReceiverModule or eNBReceiverModule. A clear split between the difference should be implemented. This can be done by adding a datatype to each receiver module thus aggregating the metrics/waveforms in a data structure which naming makes sense.

For instance:

User.Rx.RxPwdBm should be moved to User.Rx.ChannelCondition.RxPwdBm thus indiciating that the power is computed in the channel and not an estimation made at the receiver. Same for SINR and SNR.

**Comment by jakthra** [comment]
#109

**Comment by artuso0matteo** [comment]
Resolved by PR #109
