### ISSUE TITLE
User queues never updated.

### ISSUE THREAD

**Issue by MonsterMarkus** [Sonohi/monster#119]
When updating queues data is added and old data is never removed from a users queue. This leads to an ever increasing queue for all users, thus running longer simulations, will always resolve in a full buffer scenario. Se picture below.

![image](https://user-images.githubusercontent.com/42966266/66548777-34efa400-eb42-11e9-9826-0fa73bcc25b2.png)

To reproduce, any simulation can be run and the queues examined during the simulation. The queues only increase, no matter the amount of traffic transmitted.

When data is transmitted to a user, the queue should be updated, such that the data no longer is there.

**Comment by jakthra** [comment]
See #122 for possible fix

**Comment by artuso0matteo** [comment]
Closing as it has been addressed by PR #122
