### ISSUE TITLE
replaySimulation no longer working with new metrics recorder

### ISSUE THREAD

**Issue by jakthra** [Sonohi/monster#25]
- [x] Fix load of results
- [x] Refactorize plots into seperation functions for use with new GUI

**Comment by jakthra** [comment]
Work is being done on branch https://github.com/Sonohi/monster/tree/issue25-new-plotting-features

**Comment by jakthra** [comment]
Plot overhaul completed. Will create script that can replay using these.

**Comment by jakthra** [comment]
Work being done on branch issue25_replaySimulation_fix

**Comment by artuso0matteo** [comment]
Closing as completed in PR #64
