### ISSUE TITLE
Add mapping between channel regions

### ISSUE THREAD

**Issue by jakthra** [Sonohi/monster#48]
ITU has a long list of regions, same goes for WINNER and eHATA. Need a mapping function that checks the correct is used.

**Comment by jakthra** [comment]
Found missing mapping between Param.channel.region and winner. See `setPropagationScenario` . Will create a parent structure in the channel for handling region type parameters.

**Comment by jakthra** [comment]
See #53

**Comment by artuso0matteo** [comment]
Solved by #53 and closing
