### ISSUE TITLE
Implementation of variable traffic model

### ISSUE THREAD

**Issue by TR1324** [Sonohi/monster#51]
Implementation of a variable traffic model so that UEs can have different traffic arrival patterns, such as the Poisson arrival process.
It could be interesting if the traffic types could be mixed, such that some UEs follow the video streaming model while others follows the full buffer model.

**Comment by jakthra** [comment]
A class for this has been merged into master. See https://sonohi.github.io/monster/traffic.html

Traffic types are also listed. The mixing can be done in `initParam`
