### ISSUE TITLE
Using resource grid to determine number of available PRB in schedule

### ISSUE THREAD

**Issue by MonsterMarkus** [Sonohi/monster#86]
In the schedule function (line 16), the calculated available PRB are taken from the resource grid, which is unavailable as it is done later. This means that nothing is scheduled at all. The schedule function should be able to calculate the number of available PRBs based on round a configuration, making it independent from the resource grid. 

It does seem out of place to have such an eNB specific function unintegrated within the eNB class.

**Comment by artuso0matteo** [comment]
Solved in the class refactoring that has been merged to master
