### ISSUE TITLE
computeLinkBudget should return a scalar

### ISSUE THREAD

**Issue by artuso0matteo** [Sonohi/monster#87]
The bug happens when setting 1 eNodeB per type and setting the MacroEnb.radius to 500

**Comment by jakthra** [comment]
computeLinkBudget complains, but in reality this is `loss3gpp38901` that returns a vector. It should return a scalar.

**Comment by MonsterMarkus** [comment]
I am unable to reproduce the error. I have set 1 of each eNodeB type and the radius to 500, but the error does not appear.

**Comment by jakthra** [comment]
Fixed in pull request #88
