### ISSUE TITLE
Channel estimation in uplink needs to consider all configured pilots

### ISSUE THREAD

**Issue by jakthra** [Sonohi/monster#97]
Currently, it's only dependent on the configuration of the UE and the round, meaning such optional pilots as SRS are not considered.

**Comment by artuso0matteo** [comment]
@jakthra it would be a good idea to include also an option in the settings to toggle SRS usage on and off

**Comment by jakthra** [comment]
See #110

**Comment by artuso0matteo** [comment]
Closing this branch as PR  #110 has been merged into master
